1. 404 에러처리

	맨 마지막에 다음 코드 작성

	app.use((request, response, next) => {
   		response.status(404).send("can not found");
	});

	-> 라우터들을 쭉 찾다가 못찾아서 실행이 안되면 실행됨
	-> 물론 listen 앞에 써야한다.


2. 일반적 에러 처리

	다음 함수를 예시로 해보자. 
	
	fs.readFile(`data/${filteredId}`, "utf8", (err, description) => {
      		if (err) {
         		next(err);
      		} else

	-> readFile 은 파일을 찾이 못할 경우 err에 error를 넣어줌

	-> 따라서 그 안에서 err가 있을 경우 next(err)를 해줌

	-> 이때 next() 는 아무것도 없거나, 'route' 일 경우 정상호출이고, 그 외에 값일 경우엔 에러라고 약속되어있음

	-> 따라서 에러를 발생시킴

	-> 그리고 이 에러를 가공하기 위해선 다음 코드를 작성



	app.use((err, request, response, next) => {
   		console.error(err.stack);
   		response.status(500).send("error!");
	});


	-> 이렇게 인자가 4개인 콜백이 들어오면 이건 에러처리 함수라고 약속되어있음

	-> 이 함수는 404 에러 뒤에 넣어줘야함.

	-> 여기서 어디서든 발생한 에러를 잡아서 처리해줌.











